name: Deploy Python project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'createListing'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.9'
  AZURE_RESOURCE_GROUP: 'createlisting'  # Reemplaza con el nombre de tu grupo de recursos

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Create ZIP package
        run: |
          rm -f functionapp.zip
          # Se asume que host.json y las carpetas de funciones (con sus function.json) están en la raíz
          zip -r functionapp.zip * -x "*.git*"

      - name: Set WEBSITE_RUN_FROM_PACKAGE App Setting
        uses: azure/cli@v1
        with:
          inlineScript: |
            az functionapp config appsettings set --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --settings WEBSITE_RUN_FROM_PACKAGE=1

      - name: Deploy to Azure Function App via Zip Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: functionapp.zip